remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Chess Trainer!"
description: "Play a game or use the training tool, chess at your fingertips.
author:
  name: "Marshall Eldridge"


  copyright: true  